In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel("clean_coast_data.xlsx")

In [2]:
#sameeee coast number
df.loc[(df.coast_name == 'חוף כזיב') | (df.coast_name == 'כזיב')]['coast_num'].unique()
df.loc[(df.coast_name == 'חוף בצת') | (df.coast_name == 'בצת')]['coast_num'].unique()

#change the name to one of em
df.loc[df['coast_name'] == 'כזיב', 'coast_name'] = 'חוף כזיב'
df.loc[df['coast_name'] == 'בצת', 'coast_name'] = 'חוף בצת'

add distance from port ashdod

In [3]:
ashdod_port = (31.82803555650259, 34.65294228673902)
#we have 2 beaches with the same name, one is in eilat the other in tel aviv apperantly
lighthouse_center_coast = (32.10333081350449, 34.77694988873057)

In [4]:
from geopy.distance import geodesic


cords = pd.read_excel("coordinates.xlsx")


# Merge the DataFrames on 'coast_name'
merged_df = df.merge(cords, left_on='coast_name',right_on='coast_name')
# merged_df
merged_df.loc[((merged_df['coast_name'] == 'חוף המגדלור') & (merged_df.Area == 'Center')), 'lat'] = lighthouse_center_coast[0]
merged_df.loc[((merged_df['coast_name'] == 'חוף המגדלור') & (merged_df.Area == 'Center')), 'lon'] = lighthouse_center_coast[1]

In [5]:
merged_df

,Unnamed: 0_x,coast_num,Area,Distance from gaza,center,city rank,bathing_season,summer_vaction,winter,river,...,sore_lengh,city,check station,key,temp avg 3 days,distance_to_ashdod_port,have_rained,Unnamed: 0_y,lat,lon
0,0,1,North,211.4,0,7,0,0,1,0,...,25,מטה אשר,שבי ציון,שבי ציון44926,19.766667,141.321039,1,0,33.044437,35.101045
1,113,1,North,211.4,0,7,0,0,1,0,...,25,מטה אשר,שבי ציון,שבי ציון44910,NaN,141.321039,0,0,33.044437,35.101045
2,179,1,North,211.4,0,7,0,0,0,0,...,25,מטה אשר,שבי ציון,שבי ציון44895,23.533333,141.321039,0,0,33.044437,35.101045
3,245,1,North,211.4,0,7,0,0,0,0,...,25,מטה אשר,שבי ציון,שבי ציון44880,25.966667,141.321039,1,0,33.044437,35.101045
4,310,1,North,211.4,0,7,0,0,0,0,...,25,מטה אשר,שבי ציון,שבי ציון44865,27.466667,141.321039,1,0,33.044437,35.101045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25893,25564,98,Center,102.8,1,8,1,0,0,0,...,0,הרצליה,הכפר הירוק,הכפר הירוק38614,29.000000,3.256870,0,77,32.194661,34.805881
25894,25619,98,Center,102.8,1,8,1,0,0,0,...,0,הרצליה,הכפר הירוק,הכפר הירוק38599,29.766667,3.256870,0,77,32.194661,34.805881
25895,25720,98,Center,102.8,1,8,1,1,0,0,...,0,הרצליה,הכפר הירוק,הכפר הירוק38567,30.033333,12.716676,0,77,32.194661,34.805881
25896,25799,98,Center,102.8,1,8,1,1,0,0,...,0,הרצליה,הכפר הירוק,הכפר הירוק38553,29.466667,12.716676,0,77,32.194661,34.805881
25897,25870,98,Center,102.8,1,8,1,0,0,0,...,0,הרצליה,הכפר הירוק,הכפר הירוק38503,25.333333,43.145659,0,77,32.194661,34.805881

In [6]:
def get_distance(row):
    lat= row['lat']
    lon= row['lon']
    return geodesic((lat,lon),ashdod_port).km

merged_df['distance_to_ashdod_port'] = merged_df.apply(lambda row: get_distance(row), axis=1)

In [7]:
merged_df.drop(['Unnamed: 0_y', 'lat', 'lon','Unnamed: 0_x'], axis = 1, inplace=True)

In [10]:
# merged_df.to_excel("clean_coast_data.xlsx")

In [9]:
a = merged_df[['distance_to_ashdod_port','coast_name']]
a.loc[(a.coast_name == 'חוף נהריה דרום') | (a.coast_name == 'חוף דור')]

      distance_to_ashdod_port      coast_name
2059               138.227045  חוף נהריה דרום
2060               138.227045  חוף נהריה דרום
2061               138.227045  חוף נהריה דרום
2062               138.227045  חוף נהריה דרום
2063               138.227045  חוף נהריה דרום
...                       ...             ...
6662                94.916059         חוף דור
6663                94.916059         חוף דור
6664                94.916059         חוף דור
6665                94.916059         חוף דור
6666                94.916059         חוף דור

[842 rows x 2 columns]

In [43]:
df['have_rained'] = (
    (df['rain'].fillna(0.0).astype(bool) |
     df['rain-1day'].fillna(0.0).astype(bool) |
     df['rain-2days'].fillna(0.0).astype(bool) |
     df['rain-3days'].fillna(0.0).astype(bool))
).astype(int)
df[['rain', 'rain-1day', 'rain-2days', 'rain-3days','have_rained']]

       rain  rain-1day  rain-2days  rain-3days  have_rained
0       0.0        0.0         0.0         0.1            1
1       0.0        0.0         0.0         0.1            1
2       0.0        0.0         0.0         0.1            1
3       0.0        0.0         0.0         0.1            1
4       0.0        0.0         0.0         0.1            1
...     ...        ...         ...         ...          ...
25893   0.0        0.0         0.0         0.0            0
25894   0.0        0.0         0.0         0.0            0
25895   0.0        0.0         0.0         0.0            0
25896   0.0        0.0         0.0         0.0            0
25897   0.0        0.0         0.0         0.0            0

[25898 rows x 5 columns]

In [44]:
df.drop(['temperture ','temp-1day','temp-2days','rain', 'rain-1day', 'rain-2days', 'rain-3days'],axis=1,inplace=True)

In [46]:
df.to_excel("clean_coast_data.xlsx")