In [1]:
import pandas as pd
import scipy.stats as stats
df = pd.read_excel("../clean_coast_data.xlsx")

In [2]:
import numpy as np # for linear algebra operations
import plotly.graph_objects as go # for visualization

In [3]:
corr_df = df.corr()
fig = go.Figure()
fig.add_traces(go.Heatmap(
    z=corr_df, 
    x= corr_df.columns, 
    y= corr_df.columns,
))
fig.update_layout({
    'title':"Coasts Correlation Heatmap",

})
fig.show()

In [4]:
for index in corr_df.index:
  corr_values = []
  for col in corr_df.columns:
    if index!=col and abs(corr_df[index][col])>0.85:
      corr_values.append(col)
  if len(corr_values) > 0:
    print(index+ ' is correlated to: \n' , corr_values)

Unnamed: 0 is correlated to:
 ['coast_num']
coast_num is correlated to:
 ['Unnamed: 0']
Distance from gaza is correlated to:
 ['hifa_port_dis', 'distance_to_ashdod_port']
hifa_port_dis is correlated to:
 ['Distance from gaza']
distance_to_ashdod_port is correlated to:
 ['Distance from gaza']

In [3]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.columns

Index(['coast_num', 'Area', 'Distance from gaza', 'center', 'city rank',
       'bathing_season', 'summer_vaction', 'winter', 'river', 'military',
       'nature', 'coast_name', 'coast_desc', 'Date test', 'test_result',
       'test_result_num', 'month', 'year', 'city_jinny_ranking',
       'hifa_port_dis', 'sore_lengh', 'city', 'check station', 'key',
       'temp avg 3 days', 'distance_to_ashdod_port', 'have_rained'],
      dtype='object')

In [4]:
#get data from 2016 onwards.
df_2016 = df.loc[df.year >= 2016]
df_2016_eilat = df_2016.loc[df_2016.Area == 'Eilat'] #just eilat coasts
df_2016_rest = df_2016.loc[df_2016.Area != 'Eilat']
df_2016_eilat

,coast_num,Area,Distance from gaza,center,city rank,bathing_season,summer_vaction,winter,river,military,...,year,city_jinny_ranking,hifa_port_dis,sore_lengh,city,check station,key,temp avg 3 days,distance_to_ashdod_port,have_rained
12807,33,Eilat,NaN,0,6,0,0,1,0,0,...,2022,0.3625,NaN,40,אילת,אילת,אילת44926,21.433333,254.839660,1
12808,33,Eilat,NaN,0,6,0,0,1,0,0,...,2022,0.3625,NaN,40,אילת,אילת,אילת44910,27.266667,254.839660,0
12809,33,Eilat,NaN,0,6,0,0,0,0,0,...,2022,0.3625,NaN,40,אילת,אילת,אילת44895,26.333333,254.839660,0
12810,33,Eilat,NaN,0,6,0,0,0,0,0,...,2022,0.3625,NaN,40,אילת,אילת,אילת44880,29.400000,254.839660,0
12811,33,Eilat,NaN,0,6,0,0,0,0,0,...,2022,0.3625,NaN,40,אילת,אילת,אילת44865,31.300000,254.839660,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23362,78,Eilat,NaN,0,6,1,0,0,0,0,...,2016,0.3625,NaN,0,אילת,אילת,אילת42444,28.500000,259.116864,0
23363,78,Eilat,NaN,0,6,0,0,1,0,0,...,2016,0.3625,NaN,0,אילת,אילת,אילת42428,30.233333,259.116864,0
23364,78,Eilat,NaN,0,6,0,0,1,0,0,...,2016,0.3625,NaN,0,אילת,אילת,אילת42409,21.033333,259.116864,0
23365,78,Eilat,NaN,0,6,0,0,1,0,0,...,2016,0.3625,NaN,0,אילת,אילת,אילת42395,17.266667,259.116864,1
23366,78,Eilat,NaN,0,6,0,0,1,0,0,...,2016,0.3625,NaN,0,אילת,אילת,אילת42380,22.966667,259.116864,0

In [10]:
df_2016_eilat.isna().sum()

coast_num                    0
Area                         0
Distance from gaza         787
center                       0
city rank                    0
bathing_season               0
summer_vaction               0
winter                       0
river                        0
military                     0
nature                       0
coast_name                   0
coast_desc                  25
Date test                    0
test_result                  0
test_result_num              0
month                        0
year                         0
city_jinny_ranking           0
hifa_port_dis              787
sore_lengh                   0
city                         0
check station                0
key                          0
temp avg 3 days              0
distance_to_ashdod_port      0
have_rained                  0
dtype: int64

In [21]:
df_2016_eilat[['test_result']]

       test_result
12807            5
12808            5
12809            5
12810            5
12811            4
...            ...
23362            1
23363            2
23364            2
23365            2
23366            2

[787 rows x 1 columns]

In [9]:
# test_df = df.dropna()
columns_to_test = ['city rank','Distance from gaza','hifa_port_dis','distance_to_ashdod_port']
target_col = 'test_result_num'
for col in columns_to_test:
    # # Calculate the Spearman rank correlation between two columns
    rho, p_value = stats.spearmanr(df_2016_rest[target_col], df_2016_rest[col])
    print("Spearman rank correlation:", round(rho,3), round(p_value,5))

# print()
#There is no variation in df_2016_eilat['city rank'] so its standard deviation is equal 
#to 0 which will result in zero division in the spearmanr() function, thereby returning a NaN.
# rho, p_value = stats.spearmanr(df_2016_eilat[target_col], df_2016_eilat['city rank'])
# print("Spearman rank correlation:", round(rho,3), round(p_value,5))

Spearman rank correlation: -0.044 2e-05
Spearman rank correlation: 0.077 0.0
Spearman rank correlation: -0.135 0.0
Spearman rank correlation: 0.11 0.0

In [6]:
dates = df_2016_rest['Date test'].view(np.int64)
rho, p_value = stats.spearmanr(df_2016_rest[target_col], dates)
print("Spearman rank correlation all sites:", round(rho,3), round(p_value,5))
dates = df_2016_eilat['Date test'].view(np.int64)
rho, p_value = stats.spearmanr(df_2016_eilat[target_col], dates)
print("Spearman rank correlation Eilat sites:", round(rho,3), round(p_value,5))

Spearman rank correlation all sites: -0.227 0.0
Spearman rank correlation Eilat sites: 0.188 0.0

In [10]:
print("Correlation using all sites")
summer_vac_res = df_2016_rest.loc[df_2016_rest['summer_vaction'] == 1][['test_result_num','Date test']]
winter_res = df_2016_rest.loc[df_2016_rest['winter'] == 1][['test_result_num','Date test']]
# eilat_res = df.loc[df['Area'] == 'Eilat'][['test_result','Date test']]
subsets = [summer_vac_res, winter_res ]
for subset in subsets:
    subset['Date test'] = subset['Date test'].view(np.int64)
    rho, p_value = stats.spearmanr(subset.test_result_num, subset['Date test'])
    print("Spearman rank correlation:", round(rho,3), round(p_value,5))

print()
print("Correlation using Eilat sites")

summer_vac_res = df_2016_eilat.loc[df_2016_eilat['summer_vaction'] == 1][['test_result_num','Date test']]
winter_res = df_2016_eilat.loc[df_2016_eilat['winter'] == 1][['test_result_num','Date test']]
# eilat_res = df.loc[df['Area'] == 'Eilat'][['test_result','Date test']]
subsets = [summer_vac_res, winter_res ]
for subset in subsets:
    subset['Date test'] = subset['Date test'].view(np.int64)
    rho, p_value = stats.spearmanr(subset.test_result_num, subset['Date test'])
    print("Spearman rank correlation:", round(rho,3), round(p_value,5))

Correlation using all sites
Spearman rank correlation: -0.199 0.0
Spearman rank correlation: -0.193 0.0

Correlation using Eilat sites
Spearman rank correlation: 0.551 0.0
Spearman rank correlation: -0.011 0.87503