In [1]:
import pandas as pd
import scipy.stats as stats
import numpy as np # for linear algebra operations
import plotly.graph_objects as go # for visualization
df = pd.read_excel("../clean_coast_data.xlsx")

In [31]:
df.head()

,Unnamed: 0,coast_num,Area,Distance from gaza,center,city rank,bathing_season,summer_vaction,winter,river,...,year,city_jinny_ranking,hifa_port_dis,sore_lengh,city,check station,key,temp avg 3 days,distance_to_ashdod_port,have_rained
0,0,1,North,211.4,0,7,0,0,1,0,...,2022,0.4255,40.0,25,מטה אשר,שבי ציון,שבי ציון44926,19.766667,141.321039,1
1,1,1,North,211.4,0,7,0,0,1,0,...,2022,0.4255,40.0,25,מטה אשר,שבי ציון,שבי ציון44910,NaN,141.321039,0
2,2,1,North,211.4,0,7,0,0,0,0,...,2022,0.4255,40.0,25,מטה אשר,שבי ציון,שבי ציון44895,23.533333,141.321039,0
3,3,1,North,211.4,0,7,0,0,0,0,...,2022,0.4255,40.0,25,מטה אשר,שבי ציון,שבי ציון44880,25.966667,141.321039,1
4,4,1,North,211.4,0,7,0,0,0,0,...,2022,0.4255,40.0,25,מטה אשר,שבי ציון,שבי ציון44865,27.466667,141.321039,1

In [36]:
cols_to_test = ['bathing_season', 'summer_vaction','winter','nature','river','military','have_rained']
for col in cols_to_test:
    negative = df.loc[(df[col] == 0)][['test_result_num']].dropna()
    positive = df.loc[(df[col] == 1)][['test_result_num']].dropna()
    stat, p = stats.mannwhitneyu(positive.test_result_num, negative.test_result_num,alternative='two-sided')
    std_0,mean_0,median_0 = negative.std(),negative.mean(),negative.median()
    std_1,mean_1,median_1 = positive.std(),positive.mean(),positive.median()

    print("positive group values: std=%.3f, mean=%.3f, median=%.4f" %(std_1, mean_1,median_1))
    print("negative group values: std=%.3f, mean=%.3f, median=%.4f" %(std_0, mean_0,median_0))

    print('stat=%.3f, p=%.5f' % (stat, p))
    if p > 0.05:
        print(f"""{col}: Probably the same distribution"""+'\n')
    else:
        print(f"""{col}: Probably different distributions"""+'\n')

positive group values: std=36.466, mean=5.371, median=3.6700
negative group values: std=50482.517, mean=513.314, median=3.5600
stat=80773663.000, p=0.00387
bathing_season: Probably different distributions

positive group values: std=63.713, mean=6.031, median=3.7100
negative group values: std=34823.307, mean=246.905, median=3.6000
stat=54760564.500, p=0.01080
summer_vaction: Probably different distributions

positive group values: std=65358.400, mean=857.135, median=3.7500
negative group values: std=32.774, mean=5.265, median=3.6000
stat=59651884.500, p=0.13348
winter: Probably the same distribution

positive group values: std=5.139, mean=4.544, median=3.0000
negative group values: std=33781.953, mean=232.975, median=3.7500
stat=38198583.000, p=0.00000
nature: Probably different distributions

positive group values: std=5.251, mean=5.584, median=4.2500
negative group values: std=35015.527, mean=249.688, median=3.4700
stat=62940955.000, p=0.00000
river: Probably different distributions

positive group values: std=3.028, mean=3.607, median=2.7500
negative group values: std=31327.242, mean=200.994, median=3.6300
stat=2952728.500, p=0.00000
military: Probably different distributions

positive group values: std=57842.500, mean=672.459, median=3.7300
negative group values: std=34.166, mean=5.273, median=3.5900
stat=70590145.000, p=0.00550
have_rained: Probably different distributions

In [33]:
areas = df['Area'].unique()
areas_dict = {x:list(df.loc[(df['Area'] == x)]['test_result_num']) for x in areas}
[print(f"{area}: std=%.3f, mean=%.3f, median=%.4f" 
       %(np.std(areas_dict[area]), np.mean(areas_dict[area]),np.median(areas_dict[area]))) for area in areas_dict.keys()]

for i in range(len(areas) - 1):
    for j in range(i+1, len(areas)):
        if areas[i] != areas[j]:
            area = areas_dict[areas[i]]
            area_to_compare_to = areas_dict[areas[j]]

            stat, p = stats.mannwhitneyu(area, area_to_compare_to,alternative='two-sided')

            std_0,mean_0,median_0 = np.std(area), np.mean(area),np.median(area)
            std_1,mean_1,median_1 = np.std(area_to_compare_to), np.mean(area_to_compare_to),np.median(area_to_compare_to)


            print('stat=%.3f, p=%.8f' % (stat, p))
            if p > 0.05:
                print(f"""{areas[i]} vs {areas[j]}: Probably the same distribution"""+'\n')
            else:
                print(f"""{areas[i]} vs {areas[j]}: Probably different distributions"""+'\n')

North: std=46754.653, mean=441.484, median=3.9100
Center: std=4.424, mean=4.348, median=3.3100
Eilat: std=5.336, mean=3.444, median=2.0000
South: std=63.881, mean=6.666, median=4.0900
stat=48890908.500, p=0.00000000
North vs Center: Probably different distributions

stat=14510726.000, p=0.00000000
North vs Eilat: Probably different distributions

stat=30037820.000, p=0.32209852
North vs South: Probably the same distribution

stat=8420376.000, p=0.00000000
Center vs Eilat: Probably different distributions

stat=16641867.500, p=0.00000000
Center vs South: Probably different distributions

stat=2900641.500, p=0.00000000
Eilat vs South: Probably different distributions

In [3]:
authorities = pd.read_excel("../authorities.xlsx")
authorities = authorities[['coast_name','local_authority']]
authorities

             coast_name local_authority
0             חוף אכזיב           נהריה
1       חוף בוסתן הגליל         מטה אשר
2               חוף בצת         מטה אשר
3         חוף חצרות יסף         מטה אשר
4              חוף כזיב           נהריה
..                  ...             ...
74           טירת הכרמל      טירת הכרמל
75             חוף כרמל       חוף הכרמל
76          חוף הצוללים         גן רווה
77              גן רווה         גן רווה
78  אפולוניה- סידני עלי          הרצליה

[79 rows x 2 columns]

In [ ]:
merged_df = df.merge(authorities, left_on='coast_name',right_on='coast_name')

In [29]:
import pandas as pd
from scipy import stats

# Assuming df is your DataFrame

# Add 'local_authority' to the cols_to_test list
cols_to_test = ['bathing_season', 'summer_vaction', 'winter', 'nature', 'river', 'military', 'rain']

# Iterate through unique local_authority values
for local_authority_value in merged_df['local_authority'].unique():
    print(f"Local Authority: {local_authority_value}")
    
    # Filter DataFrame for the specific local_authority
    local_authority_df = merged_df[merged_df['local_authority'] == local_authority_value]

    # Iterate through the columns for statistical analysis
    for col in cols_to_test:  # Skip the 'local_authority' column
        if col in local_authority_df.columns:
            negative = local_authority_df.loc[(local_authority_df[col] == 0)][['test_result_num']].dropna()
            positive = local_authority_df.loc[(local_authority_df[col] == 1)][['test_result_num']].dropna()

            # Perform the Mann-Whitney U test
            stat, p = stats.mannwhitneyu(positive.test_result_num, negative.test_result_num, alternative='two-sided')

            # Calculate statistics for both groups
            std_0, mean_0, median_0 = negative.std(), negative.mean(), negative.median()
            std_1, mean_1, median_1 = positive.std(), positive.mean(), positive.median()

            # Print the results
            print(f"{col}:")
            print("Positive group values - std=%.3f, mean=%.3f, median=%.4f" % (std_1, mean_1, median_1))
            print("Negative group values - std=%.3f, mean=%.3f, median=%.4f" % (std_0, mean_0, median_0))
            print('stat=%.3f, p=%.5f' % (stat, p))

            # Check for significance and print the result
            if p > 0.05:
                print("Probably the same distribution\n")
            else:
                print("Probably different distributions\n")

Local Authority: נהריה
bathing_season:
Positive group values - std=4.806, mean=5.144, median=3.6000
Negative group values - std=6.515, mean=5.487, median=3.3300
stat=531336.000, p=0.27592
Probably the same distribution

summer_vaction:
Positive group values - std=5.045, mean=5.400, median=3.8000
Negative group values - std=5.634, mean=5.244, median=3.4500
stat=366604.000, p=0.07363
Probably the same distribution

winter:
Positive group values - std=6.786, mean=5.967, median=3.6300
Negative group values - std=5.084, mean=5.075, median=3.5000
stat=392905.500, p=0.29483
Probably the same distribution

nature:
Positive group values - std=3.620, mean=3.541, median=2.4000
Negative group values - std=5.823, mean=5.708, median=4.0000
stat=233151.000, p=0.00000
Probably different distributions

river:
Positive group values - std=5.958, mean=5.659, median=3.7500
Negative group values - std=4.740, mean=4.699, median=3.2100
stat=585894.500, p=0.00001
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=5.522, mean=5.275, median=3.5000
stat=0.000, p=0.00000
Probably different distributions

Local Authority: מטה אשר
bathing_season:
Positive group values - std=6.000, mean=4.805, median=2.8700
Negative group values - std=5.317, mean=4.497, median=2.7100
stat=506054.000, p=0.27854
Probably the same distribution

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

summer_vaction:
Positive group values - std=6.560, mean=5.654, median=3.2500
Negative group values - std=5.505, mean=4.445, median=2.6700
stat=390474.000, p=0.00000
Probably different distributions

winter:
Positive group values - std=5.899, mean=4.707, median=2.8100
Negative group values - std=5.712, mean=4.683, median=2.8100
stat=354113.500, p=0.68991
Probably the same distribution

nature:
Positive group values - std=6.557, mean=4.844, median=2.6300
Negative group values - std=4.262, mean=4.455, median=3.0500
stat=456894.000, p=0.00050
Probably different distributions

river:
Positive group values - std=6.038, mean=5.269, median=3.2950
Negative group values - std=5.530, mean=4.314, median=2.6050
stat=558250.500, p=0.00001
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=5.752, mean=4.688, median=2.8100
stat=0.000, p=0.00000
Probably different distributions

Local Authority: עכו
bathing_season:
Positive group values - std=5.482, mean=5.783, median=4.2900
Negative group values - std=4.390, mean=4.481, median=2.9400
stat=98288.000, p=0.00001
Probably different distributions

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

summer_vaction:
Positive group values - std=6.865, mean=7.130, median=5.4200
Negative group values - std=4.473, mean=4.812, median=3.5100
stat=69112.000, p=0.00000
Probably different distributions

winter:
Positive group values - std=3.790, mean=3.951, median=2.7200
Negative group values - std=5.399, mean=5.676, median=4.1900
stat=48488.500, p=0.00000
Probably different distributions

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=5.119, mean=5.273, median=3.7800
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=5.119, mean=5.273, median=3.7800
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=5.119, mean=5.273, median=3.7800
stat=0.000, p=0.00000
Probably different distributions

Local Authority: חדרה
bathing_season:
Positive group values - std=3.589, mean=4.932, median=4.1300
Negative group values - std=3.447, mean=4.802, median=3.9400
stat=189474.000, p=0.44307
Probably the same distribution

summer_vaction:
Positive group values - std=3.742, mean=5.156, median=4.3250
Negative group values - std=3.477, mean=4.811, median=4.0000
stat=140359.500, p=0.08115
Probably the same distribution

winter:
Positive group values - std=3.491, mean=4.871, median=4.0450
Negative group values - std=3.550, mean=4.887, median=4.0500
stat=136386.000, p=0.92072
Probably the same distribution

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=3.536, mean=4.884, median=4.0500
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=3.083, mean=4.522, median=3.8900
Negative group values - std=3.732, mean=5.066, median=4.2100
stat=163882.000, p=0.03970
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=3.536, mean=4.884, median=4.0500
stat=0.000, p=0.00000
Probably different distributions

Local Authority: עמק חפר
bathing_season:
Positive group values - std=2.740, mean=3.726, median=3.1100
Negative group values - std=5.838, mean=4.226, median=3.4000
stat=81823.500, p=0.39936
Probably the same distribution

summer_vaction:
Positive group values - std=2.821, mean=3.958, median=3.1850
Negative group values - std=4.481, mean=3.904, median=3.2600
stat=61103.000, p=0.40977
Probably the same distribution

winter:
Positive group values - std=7.219, mean=4.660, median=3.6000
Negative group values - std=2.698, mean=3.696, median=3.1100
stat=68096.500, p=0.10955
Probably the same distribution

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.194, mean=3.915, median=3.2400
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.194, mean=3.915, median=3.2400
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.194, mean=3.915, median=3.2400
stat=0.000, p=0.00000
Probably different distributions

Local Authority: ג'סר א-זרקא
bathing_season:
Positive group values - std=6.677, mean=6.973, median=4.5450
Negative group values - std=8.341, mean=6.605, median=4.0000
stat=22606.000, p=0.21477
Probably the same distribution

summer_vaction:
Positive group values - std=4.330, mean=6.310, median=4.7900
Negative group values - std=7.936, mean=6.967, median=4.2700
stat=15169.000, p=0.50317
Probably the same distribution

winter:
Positive group values - std=9.837, mean=6.928, median=4.4000
Negative group values - std=6.443, mean=6.805, median=4.3650
stat=15404.000, p=0.70055
Probably the same distribution

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=7.347, mean=6.833, median=4.3800
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=7.347, mean=6.833, median=4.3800
Negative group values - std=nan, mean=nan, median=nan
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=7.347, mean=6.833, median=4.3800
stat=0.000, p=0.00000
Probably different distributions

Local Authority: חוף הכרמל
bathing_season:
Positive group values - std=4.342, mean=5.548, median=4.5300
Negative group values - std=6.131, mean=5.530, median=4.3550
stat=2431527.000, p=0.01324
Probably different distributions

summer_vaction:
Positive group values - std=3.793, mean=5.271, median=4.3700
Negative group values - std=5.370, mean=5.609, median=4.4850
stat=1590352.500, p=0.85749
Probably the same distribution

winter:
Positive group values - std=5.017, mean=5.547, median=4.4700
Negative group values - std=5.118, mean=5.539, median=4.4600
stat=1704087.500, p=0.32650
Probably the same distribution

nature:
Positive group values - std=4.506, mean=4.553, median=3.2050
Negative group values - std=5.257, mean=5.925, median=4.9100
stat=1480674.000, p=0.00000
Probably different distributions

river:
Positive group values - std=5.382, mean=5.767, median=4.1500
Negative group values - std=5.050, mean=5.507, median=4.4900
stat=1101994.000, p=0.36856
Probably the same distribution

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=5.095, mean=5.541, median=4.4600
stat=0.000, p=0.00000
Probably different distributions

Local Authority: נתניה
bathing_season:
Positive group values - std=3.907, mean=4.331, median=3.1750
Negative group values - std=4.891, mean=4.777, median=3.3300
stat=221711.000, p=0.74775
Probably the same distribution

summer_vaction:
Positive group values - std=3.773, mean=4.640, median=3.6650
Negative group values - std=4.431, mean=4.460, median=3.1300
stat=173111.500, p=0.00810
Probably different distributions

winter:
Positive group values - std=5.566, mean=5.630, median=3.8950
Negative group values - std=3.817, mean=4.178, median=3.0000
stat=189251.000, p=0.00005
Probably different distributions

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.303, mean=4.497, median=3.2200
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=3.160, mean=3.072, median=2.0000
Negative group values - std=4.374, mean=4.635, median=3.3300
stat=54612.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.303, mean=4.497, median=3.2200
stat=0.000, p=0.00000
Probably different distributions

Local Authority: חיפה
bathing_season:
Positive group values - std=6.573, mean=6.596, median=4.7800
Negative group values - std=207493.724, mean=8593.152, median=4.9150
stat=255620.000, p=0.18997
Probably the same distribution

summer_vaction:
Positive group values - std=5.213, mean=6.118, median=4.5100
Negative group values - std=143972.981, mean=4140.713, median=4.9300
stat=163298.000, p=0.20245
Probably the same distribution

winter:
Positive group values - std=266884.945, mean=14211.378, median=4.8300
Negative group values - std=8.307, mean=6.824, median=4.8200
stat=206485.000, p=0.50361
Probably the same distribution

nature:
Positive group values - std=5.683, mean=8.081, median=7.6900
Negative group values - std=137649.920, mean=3785.268, median=4.6700
stat=143080.500, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=129641.967, mean=3358.567, median=4.8250
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=129641.967, mean=3358.567, median=4.8250
stat=0.000, p=0.00000
Probably different distributions

Local Authority: טירת הכרמל

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

bathing_season:
Positive group values - std=4.611, mean=6.984, median=5.5700
Negative group values - std=3.658, mean=5.588, median=4.9850
stat=21278.500, p=0.00426
Probably different distributions

summer_vaction:
Positive group values - std=4.541, mean=7.300, median=6.2300
Negative group values - std=4.237, mean=6.228, median=5.2100
stat=14143.000, p=0.03021
Probably different distributions

winter:
Positive group values - std=3.764, mean=5.866, median=5.2900
Negative group values - std=4.459, mean=6.616, median=5.2900
stat=12673.000, p=0.30111
Probably the same distribution

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.315, mean=6.441, median=5.2900
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.315, mean=6.441, median=5.2900
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.315, mean=6.441, median=5.2900
stat=0.000, p=0.00000
Probably different distributions

Local Authority: אילת
bathing_season:
Positive group values - std=5.631, mean=3.589, median=2.1400
Negative group values - std=3.653, mean=2.443, median=1.4500
stat=343944.000, p=0.00000
Probably different distributions

summer_vaction:
Positive group values - std=7.008, mean=3.860, median=2.0000
Negative group values - std=4.366, mean=2.975, median=1.7100
stat=202653.000, p=0.10674
Probably the same distribution

winter:
Positive group values - std=2.813, mean=2.145, median=1.3600
Negative group values - std=5.447, mean=3.449, median=1.9500
stat=184455.000, p=0.00000
Probably different distributions

nature:
Positive group values - std=nan, mean=nan, median=nan

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

Negative group values - std=4.985, mean=3.142, median=1.7600
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.985, mean=3.142, median=1.7600
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.985, mean=3.142, median=1.7600
stat=0.000, p=0.00000
Probably different distributions

Local Authority: חוף השרון
bathing_season:
Positive group values - std=6.418, mean=5.596, median=3.6950
Negative group values - std=6.503, mean=6.382, median=4.5150
stat=6797.500, p=0.24372
Probably the same distribution

summer_vaction:
Positive group values - std=4.950, mean=5.825, median=4.7550
Negative group values - std=6.757, mean=5.941, median=3.9450
stat=4921.500, p=0.53112
Probably the same distribution

winter:
Positive group values - std=7.316, mean=8.208, median=5.1400
Negative group values - std=6.013, mean=5.221, median=3.4150
stat=7415.500, p=0.00007
Probably different distributions

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=6.451, mean=5.920, median=4.0000
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=6.451, mean=5.920, median=4.0000
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=6.451, mean=5.920, median=4.0000
stat=0.000, p=0.00000
Probably different distributions

Local Authority: בת ים
bathing_season:
Positive group values - std=1.772, mean=1.335, median=0.8300
Negative group values - std=2.152, mean=1.698, median=0.7350
stat=11524.000, p=0.65460
Probably the same distribution

summer_vaction:
Positive group values - std=0.866, mean=0.889, median=0.4850
Negative group values - std=2.084, mean=1.614, median=0.8800
stat=6995.500, p=0.14780
Probably the same distribution

winter:
Positive group values - std=2.294, mean=1.872, median=0.8800
Negative group values - std=1.789, mean=1.349, median=0.8100
stat=9817.000, p=0.31174
Probably the same distribution

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=1.929, mean=1.472, median=0.8150
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=1.929, mean=1.472, median=0.8150
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=1.929, mean=1.472, median=0.8150
stat=0.000, p=0.00000
Probably different distributions

Local Authority: תל אביב-יפו
bathing_season:
Positive group values - std=2.725, mean=1.944, median=1.0000
Negative group values - std=2.906, mean=2.107, median=1.0000
stat=82841.500, p=0.93841
Probably the same distribution

summer_vaction:
Positive group values - std=2.359, mean=1.794, median=1.0000
Negative group values - std=2.897, mean=2.061, median=1.0000
stat=54554.000, p=0.25810
Probably the same distribution

winter:
Positive group values - std=2.717, mean=2.199, median=1.0000
Negative group values - std=2.816, mean=1.949, median=1.0000
stat=64473.500, p=0.32068
Probably the same distribution

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=2.794, mean=2.006, median=1.0000
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=2.794, mean=2.006, median=1.0000
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=2.794, mean=2.006, median=1.0000
stat=0.000, p=0.00000
Probably different distributions

Local Authority: הרצליה
bathing_season:
Positive group values - std=6.074, mean=4.185, median=2.2500
Negative group values - std=6.644, mean=4.303, median=2.4000
stat=81614.000, p=0.24298
Probably the same distribution

summer_vaction:
Positive group values - std=8.504, mean=4.568, median=2.5600
Negative group values - std=5.582, mean=4.141, median=2.2500
stat=58125.000, p=0.16679
Probably the same distribution

winter:
Positive group values - std=7.955, mean=4.650, median=2.4000
Negative group values - std=5.755, mean=4.114, median=2.2900
stat=54931.000, p=0.69173
Probably the same distribution

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=6.286, mean=4.228, median=2.2950
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=6.286, mean=4.228, median=2.2950
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=6.286, mean=4.228, median=2.2950
stat=0.000, p=0.00000
Probably different distributions

Local Authority: אשדוד
bathing_season:
Positive group values - std=202.748, mean=13.615, median=2.8950
Negative group values - std=3.623, mean=3.909, median=2.8200
stat=81597.500, p=0.61851
Probably the same distribution

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

summer_vaction:
Positive group values - std=357.172, mean=31.980, median=2.3100
Negative group values - std=4.843, mean=4.419, median=3.0000
stat=48341.000, p=0.04800
Probably different distributions

winter:
Positive group values - std=3.440, mean=3.887, median=2.8200
Negative group values - std=181.429, mean=11.687, median=2.8900
stat=61166.000, p=0.69491
Probably the same distribution

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=159.098, mean=9.884, median=2.8600
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=159.098, mean=9.884, median=2.8600
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=159.098, mean=9.884, median=2.8600
stat=0.000, p=0.00000
Probably different distributions

Local Authority: אשקלון
bathing_season:
Positive group values - std=3.243, mean=5.163, median=4.5000
Negative group values - std=4.435, mean=6.161, median=5.3500
stat=755742.500, p=0.00000
Probably different distributions

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

summer_vaction:
Positive group values - std=3.161, mean=4.830, median=4.1200
Negative group values - std=3.887, mean=5.717, median=5.0500
stat=502551.500, p=0.00000
Probably different distributions

winter:
Positive group values - std=4.620, mean=6.584, median=5.8700
Negative group values - std=3.423, mean=5.235, median=4.5600
stat=789480.000, p=0.00000
Probably different distributions

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=3.770, mean=5.540, median=4.8400
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=4.001, mean=6.263, median=5.5500
Negative group values - std=3.254, mean=4.652, median=3.8900
stat=1198817.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=3.770, mean=5.540, median=4.8400
stat=0.000, p=0.00000
Probably different distributions

Local Authority: רשות הטבע והגנים
bathing_season:

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

Positive group values - std=3.135, mean=3.594, median=2.9600
Negative group values - std=3.490, mean=3.638, median=2.9600
stat=141611.000, p=0.71471
Probably the same distribution

summer_vaction:
Positive group values - std=2.770, mean=3.265, median=2.6400
Negative group values - std=3.385, mean=3.697, median=3.0000
stat=88291.000, p=0.20335
Probably the same distribution

winter:
Positive group values - std=3.581, mean=3.868, median=3.2450
Negative group values - std=3.175, mean=3.532, median=2.8400
stat=111176.500, p=0.19696
Probably the same distribution

nature:
Positive group values - std=3.555, mean=3.852, median=3.2400
Negative group values - std=2.136, mean=2.913, median=2.3800
stat=125011.000, p=0.00438
Probably different distributions

river:
Positive group values - std=2.136, mean=2.913, median=2.3800
Negative group values - std=3.555, mean=3.852, median=3.2400
stat=99335.000, p=0.00438
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=3.276, mean=3.611, median=2.9600
stat=0.000, p=0.00000
Probably different distributions

Local Authority: גן רווה
bathing_season:
Positive group values - std=16.267, mean=10.158, median=4.6300
Negative group values - std=16.661, mean=9.232, median=4.1600
stat=114409.000, p=0.02294
Probably different distributions

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd

summer_vaction:
Positive group values - std=17.005, mean=10.723, median=4.8600
Negative group values - std=16.259, mean=9.584, median=4.4500
stat=76011.000, p=0.38435
Probably the same distribution

winter:
Positive group values - std=17.206, mean=9.144, median=3.7550
Negative group values - std=16.185, mean=10.006, median=4.6400
stat=70483.500, p=0.03976
Probably different distributions

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=16.411, mean=9.816, median=4.4700
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=16.411, mean=9.816, median=4.4700
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=3.028, mean=3.607, median=2.7500
Negative group values - std=18.829, mean=12.384, median=5.4600
stat=57713.500, p=0.00000
Probably different distributions

Local Authority: חוף אשקלון
bathing_season:
Positive group values - std=2.548, mean=4.385, median=4.3000
Negative group values - std=1.999, mean=4.608, median=4.7350
stat=1737.000, p=0.29746
Probably the same distribution

summer_vaction:
Positive group values - std=1.434, mean=3.418, median=3.6000
Negative group values - std=2.432, mean=4.711, median=4.5900
stat=764.500, p=0.00697
Probably different distributions

winter:
Positive group values - std=1.910, mean=5.447, median=5.2400
Negative group values - std=2.378, mean=4.177, median=4.0500
stat=2051.000, p=0.00072
Probably different distributions

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=2.333, mean=4.477, median=4.3500
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=2.333, mean=4.477, median=4.3500
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=2.333, mean=4.477, median=4.3500
stat=0.000, p=0.00000
Probably different distributions

Local Authority: קריית ים
bathing_season:
Positive group values - std=4.919, mean=5.465, median=4.0000
Negative group values - std=4.663, mean=5.520, median=3.8100
stat=82891.500, p=0.94992
Probably the same distribution

summer_vaction:
Positive group values - std=4.811, mean=5.520, median=3.8100
Negative group values - std=4.824, mean=5.478, median=3.9500
stat=55667.000, p=0.99270
Probably the same distribution

winter:
Positive group values - std=4.987, mean=5.982, median=4.3300
Negative group values - std=4.761, mean=5.338, median=3.8800
stat=66584.000, p=0.13201
Probably the same distribution

nature:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.819, mean=5.486, median=3.9200
stat=0.000, p=0.00000
Probably different distributions

river:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.819, mean=5.486, median=3.9200
stat=0.000, p=0.00000
Probably different distributions

military:
Positive group values - std=nan, mean=nan, median=nan
Negative group values - std=4.819, mean=5.486, median=3.9200
stat=0.000, p=0.00000
Probably different distributions

c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd
c:\Users\liavc\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py:7028: RuntimeWarning: divide by zero encountered in double_scalars
  z = (bigu - meanrank) / sd